services:
  db:
    image: pgvector/pgvector:pg18
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg}
      POSTGRES_DB: ${POSTGRES_DB:-cs431_db}

  # backend:
  #   build: .
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_HOST: db
  #   ports:
  #     - "${BACKEND_PORT:-8000}:8000"

volumes:
  pg_data: